- name: Prepare k8s nodes
  hosts: masters
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
#add bare name    
    - name: Adding bare hosts name
      blockinfile:
       path: "/etc/hosts"
       block: |
        172.16.2.111    master1.wheehost.com    master1
        172.16.2.112    msater2.wheehost.com    master2
       
        172.16.2.100    ha1.wheehost.com         ha1
       
        172.16.2.221    rook1.wheehost.com      rook1
        172.16.2.222    rook2.wheehost.com      rook2
        172.16.2.223    rook3.wheehost.com      rook3  

#Set time/zone    
    - name: Set timezone
      timezone:
        name: Asia/Jakarta

#update enviroment
    - name: Update system
      apt:
        name: "*"
        state: latest
        update_cache: yes

#install requirement package docker dan k8s
    - name: Install common packages
      apt:
        name: [wget,curl,apt-transport-https,ca-certificates,curl,gnupg,lsb-release]
        state: present
        update_cache: yes

#copy autorize key
    - name: Set authorized key taken from file to root user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#Add Repo Docker   
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for docker stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker

#Add Repo k8s
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

#Requirement dari k8s
#disable swap
    - name: disable swap
      shell: |
         swapoff -a
         sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

#setup kernel dan file konfigurasi              
    - name: Create containerd config file
      file:
       path: "/etc/modules-load.d/containerd.conf"
       state: "touch"

    - name: Add conf for containerd
      blockinfile:
       path: "/etc/modules-load.d/containerd.conf"
       block: |
          overlay
          br_netfilter

    - name: modprobe
      shell: |
          modprobe overlay
          modprobe br_netfilter

    - name: Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1
            net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply new settings
      command:  sysctl --system

    - name: Reboot server after update and configs
      reboot:
